var config = {
    name: "KnetTools",
    version: "1.0",
    description: "Recursos para integração com impressora",
    beta: "beta.knetapp.com.br",
    production: "app.knetapp.com.br",
    protocol: ["http://","https://"],
    baseurl: "#",
    upgrade: "",
    display: "",
    terminal: "",
    info: "prest_extension",
    servicelocal: "http://127.0.0.1:9876/com.knetapp.service.ServiceServer?wsdl",
    serviceversion: "1.0.0",
    downloadbeta:"https://dev.knetapp.com.br/download/wvetro.setup.exe",
    downloadprod:"https://www.knetapp.com.br/download/wvetro.setup.exe",
};