var config = {
    name: "wvetro",
    version: "1.0.0.0",
    description: "Recursos para aplicação wvetro",
    beta: "homol.wvetro.com.br",
    production: "sistema.wvetro.com.br",
    developer: "developer.wvetro.com.br",
    protocol: "https://",
    baseurl: "/wvetro/rest/NotaFiscal/",
    upgrade: "version",
    display: "render",
    terminal: "console",
    info: "prest_NotaFiscalExtension",
    servicelocal: "http://127.0.0.1:9876/com.knetapp.service.ServiceServer?wsdl",
    serviceversion: "1.0.0",
    downloadbeta:"https://beta.wvetro.com.br/wvetro/download/wvetro_install.exe",
    downloadprod:"https://sistema.wvetro.com.br/wvetro/download/wvetro_install.exe",
    downloaddev:"https://dev.wvetro.com.br/wvetro/download/wvetro_install.exe",
};